### ISSUE TITLE
API integration issue

### ISSUE THREAD

**Issue by ArdenCCPros** [ArdenCCPros/ONFT-Marketplace-DEV#1]
![issue](https://github.com/ArdenCCPros/ONFT-Marketplace-DEV/assets/152620473/fbc9558b-30c3-40ae-8770-2c03461c640f)

We are now on the stage to fetch ONFTs from wallet address using the moralis api.
For now, we have some issues lie the above image.

**Comment by tonyl85** [comment]
To fix this error, you need to enable CORS on your backend server. This involves adding an Access-Control-Allow-Origin header to your server's responses. The value of this header should be the origin of your React app (like http://localhost:3000), or * to allow requests from any origin.
Please give me backend access and I will fix it in a short time.

**Comment by kirangautam45** [comment]
Hi @ArdenCCPros, The error has occurred because you haven't installed CORE in the backend . as you can see in Screen Short. you just need to install and use CORE in the back end. Please give me backend access and I will fix it in a short time
![Screenshot from 2023-12-04 14-31-59](https://github.com/ArdenCCPros/ONFT-Marketplace-DEV/assets/50335198/636acd35-dfd1-4eef-a14a-1d52761a290c)

**Comment by fredgeorge0311** [comment]
Hi @ArdenCCPros 

The error message you provided indicates a network error in your JavaScript code. 

Here are a few steps you can try to fix it:

Verify the URL and endpoint: Double-check the URL and endpoint you are trying to access in your code. Ensure that it is correct and properly formatted.

Check CORS settings: Since you mentioned that you suspect a CORS issue, make sure that the server is configured to allow cross-origin requests from your frontend application. You may need to add appropriate CORS headers on the server-side.

Debugging tools: Utilize browser developer tools, such as the Network tab or console, to inspect the network requests and responses. Look for any error messages or additional information that can help pinpoint the issue.

This is a general error, so I think it is not difficult to fix this error.
